export const AUTOMATION_CYCLE_CADENCE_SECONDS = 60;

export const PAPER_BUY_RESERVATION_EXPIRY_SECONDS = 180;

export const PAPER_BUY_RESERVATION_EXPIRY_INTERVAL =
  "3 minutes";

export const AUTOMATION_CYCLE_MAX_APPROVED_ORDERS = 5;

export const AUTOMATION_CYCLE_CONTRACT = {
  cadenceSeconds:
    AUTOMATION_CYCLE_CADENCE_SECONDS,

  reservationExpirySeconds:
    PAPER_BUY_RESERVATION_EXPIRY_SECONDS,

  reservationExpiryInterval:
    PAPER_BUY_RESERVATION_EXPIRY_INTERVAL,

  expiryOpportunities:
    PAPER_BUY_RESERVATION_EXPIRY_SECONDS /
    AUTOMATION_CYCLE_CADENCE_SECONDS,

  maxApprovedOrdersPerCycle:
    AUTOMATION_CYCLE_MAX_APPROVED_ORDERS,
} as const;
